version: '3.7'

services:
  php7.2:
    container_name: php7.2
    image: php7.2
    network_mode: bridge
    volumes:
      - ./docker:/etc/php7:ro
      - ./:/var/log/php7
      #- $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum.php:ro
      #- $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum/fulcrum.php:ro
      #- $FULCRUM_HOME_DC/fulcrum/var/fulcrum/private_files:/private
      - ./:/var/www/html
    ports:
      - "9072:9000"
#    dns: $FULCRUM_HOST_IP
#    cap_add:
#      - SYS_PTRACE
  php7.3:
    container_name: php7.3
    image: php7.3
    network_mode: bridge
    volumes:
      - ./docker:/etc/php7:ro
      - ./:/var/log/php7
      #- $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum.php:ro
      #- $FULCRUM_HOME_DC/fulcrum/etc/fulcrum/php/fulcrum.php:/fulcrum/fulcrum.php:ro
      #- $FULCRUM_HOME_DC/fulcrum/var/fulcrum/private_files:/private
      - ./:/var/www/html
    ports:
      - "9073:9000"
#    dns: $FULCRUM_HOST_IP
#    cap_add:
#      - SYS_PTRACE

